parameters:
#    infogold_admin.example.class: Infogold\AdminBundle\Example

services:
#    infogold_admin.example:
#        class: %infogold_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
