infogold_search:
    resource: "@InfogoldSearchBundle/Resources/config/routing.yml"
    prefix:   /



infogold_klienci:
    resource: "@InfogoldKlienciBundle/Resources/config/routing.yml"
    prefix:   /

# Logowanie konsultanta
infogold_konsultant:
    resource: "@InfogoldKonsultantBundle/Resources/config/routing.yml"
    prefix:   /konsultant
    
# Konsultanta klienci 
klient_konsultant:
    resource: "@InfogoldKlienciBundle/Resources/config/routing.yml"
    prefix:   /konsultant
    
# Konsultanta przerwy 
przerwy_konsultant:
    resource: "@InfogoldKonsultantBundle/Resources/config/routing/przerwy.yml"
    prefix:   /konsultant
    
# Konsultanta produkty show 
produkt_konsultant:
    resource: "@InfogoldKonsultantBundle/Resources/config/routing/produkt.yml"
    prefix:   /konsultant
    
# Grafik konsultanta działu show 
grafik_konsultant:
    resource: "@InfogoldKonsultantBundle/Resources/config/routing/grafik.yml"
    prefix:   /konsultant
    
# glowna strona konsultanta
glowna_konsultanta:
    resource: "@InfogoldKonsultantBundle/Resources/config/routing/glowna.yml"
    prefix:   /konsultant

# Administracja firmy
infogold_account:
    resource: "@InfogoldAccountBundle/Resources/config/routing.yml"
    prefix:   /user
    
infogold_faktura:
    resource: "@InfogoldKlienciBundle/Resources/config/routing/faktura.yml"
    prefix:   /user
    
infogold_fosuser:
    resource: "@InfogoldAccountBundle/Resources/config/routing/fosu.yml"
    prefix: /user
    
infogold_produkty:
    resource: "@InfogoldAccountBundle/Resources/config/routing/produkty.yml"
    prefix: /user/produkty
    
infogold_ustawienia:
    resource: "@InfogoldAccountBundle/Resources/config/routing/ustawienia.yml"
    prefix: /user/profile
    
infogold_contacts_types:
    resource: "@InfogoldKlienciBundle/Resources/config/routing/rodzajekontaktow.yml"
    prefix: /user/profile/contacts-types

infogold_category:
    resource: "@InfogoldAccountBundle/Resources/config/routing/category.yml"
    prefix: /user/category
    

    
infogold_ajax:
    resource: "@InfogoldAjaxBundle/Resources/config/routing.yml"
    prefix:   /

infogold_strona:
    resource: "@InfogoldStronaBundle/Resources/config/routing.yml"
    prefix:   /

infogold_user:
    resource: "@InfogoldUserBundle/Resources/config/routing.yml"
    prefix:   /
 
  
# app/config/routing.yml
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
    
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
    
    
# administracja główna

# Logowanie mnie
infogold_admin:
    resource: "@InfogoldAdminBundle/Resources/config/routing.yml"
    prefix:   /admin
    
infogold_administracja:
    resource: "@InfogoldUserBundle/Resources/config/routing/user.yml"
    prefix:   /admin