security_login:
    pattern: /login
    defaults: { _controller: InfogoldKonsultantBundle:Security:login }
 
login_check:
    pattern: /login_check  

 #   getRoles() zmieniono w encji konsultanta
_security_logout:
    pattern: /logout
    
    
failure_path:
    pattern: /login
  
    
# admin:
#    pattern:  /admin
#    defaults: { _controller: "InfogoldKonsultantBundle:Default:index" }    
    
 
change_password:
    pattern:  /changepassword/{id}
    defaults: { _controller: "InfogoldKonsultantBundle:Security:ChangePassword" }



konsultant_password:
    pattern:  /updatepassword/{id}
    defaults: { _controller: "InfogoldKonsultantBundle:Security:UpdatePassword" }
    requirements: { _method: post|put }
    

    

   
    