infogold_klienci_faktura:
    resource: "@InfogoldKlienciBundle/Resources/config/routing/faktura.yml"
    prefix:   /faktura

klienci:
    pattern:  /klient/indywidualni
    defaults: { _controller: "InfogoldKlienciBundle:Klienci:indywidualni" }
    
klienci_firmowi:
    pattern:  /klient/firmowi
    defaults: { _controller: "InfogoldKlienciBundle:Klienci:firmowi" }
    

klienci_all_ind:
    pattern:  /klient/bazaindall
    defaults: { _controller: "InfogoldAccountBundle:Baza:bazaklientow" }
    
klienci_all_firma:
    pattern:  /klient/bazafirmaall
    defaults: { _controller: "InfogoldAccountBundle:Baza:bazaklientowfirmowych" }
    
klienci_show:
    pattern:  /klient/{id}/show
    defaults: { _controller: "InfogoldKlienciBundle:Klienci:show" }

klienci_new:
    pattern:  /klient/new
    defaults: { _controller: "InfogoldKlienciBundle:Klienci:new" }
    
klienci_new_firmowy:
    pattern:  /klient/newfirmowy
    defaults: { _controller: "InfogoldKlienciBundle:Klienci:newfirmowy" }

klienci_create:
    pattern:  /klient/create
    defaults: { _controller: "InfogoldKlienciBundle:Klienci:create" }
    requirements: { _method: post }
    
klienci_create_firmowy:
    pattern:  /klient/createfirma
    defaults: { _controller: "InfogoldKlienciBundle:Klienci:createfirma" }
    requirements: { _method: post }

klienci_edit:
    pattern:  /klient/{id}/edit
    defaults: { _controller: "InfogoldKlienciBundle:Klienci:edit" }
    
klienci_editfirmowy:
    pattern:  /klient/{id}/editfirmowy
    defaults: { _controller: "InfogoldKlienciBundle:Klienci:editfirmowy" }

klienci_delete:
    pattern:  /klient/{id}/delete
    defaults: { _controller: "InfogoldKlienciBundle:Klienci:delete" }
    requirements: { _method: post|delete }
    
# kontakt_edit:
 #   pattern:  /klient/{id}/editkontakt
 #   defaults: { _controller: "InfogoldKlienciBundle:Klienci:editKontakt" }

klienci_update:
    pattern:  /klient/{id}/update
    defaults: { _controller: "InfogoldKlienciBundle:Klienci:update" }
    requirements: { _method: post|put }
    
klienci_delete:
    pattern:  /klient/{id}/delete
    defaults: { _controller: "InfogoldKlienciBundle:Klienci:delete" }
    requirements: { _method: post|delete }
    
kontakt_save:
    pattern:  /klient/{id}/kontaktzapisz
    defaults: { _controller: "InfogoldKlienciBundle:Klienci:zapiszkontakt" }
    
kontakt_update:
    pattern:  /klient/{id}/updatekontakt
    defaults: { _controller: "InfogoldKlienciBundle:Klienci:updateKontakt" }
  
kontakt_delete:
    pattern:  /klient/{id}/deletekontakt
    defaults: { _controller: "InfogoldKlienciBundle:Klienci:deletekontakt" }
    requirements: { _method: post|delete }
    
sell_save:
    pattern:  /klient/{id}/sellsave
    defaults: { _controller: "InfogoldKlienciBundle:Klienci:zapiszsprzedaz" }
    
cena_i_dane:
    pattern:  /klient/cena
    defaults: { _controller: "InfogoldKlienciBundle:Klienci:cenaajax" }
    
fakturapronr:
    pattern:  /klient/fakturapronr
    defaults: { _controller: "InfogoldKlienciBundle:Klienci:fakturapronr" }
    
faktura_pro_create:
    pattern:  /klient/{id}/fakturaprocreate
    defaults: { _controller: "InfogoldKlienciBundle:Klienci:faktura" }
    
faktura_pdf_konsultant:
    pattern:  /klient/{id}/fakturapdf
    defaults: { _controller: "InfogoldKlienciBundle:Klienci:fakturapdf" }
    
sprzedaz_usun:
    pattern:  /klient/sprzedaz/{id}/{idzakup}
    defaults: { _controller: "InfogoldKlienciBundle:Klienci:usunsprzedaz" }
    
