admin:
    path:     /
    defaults: { _controller: "InfogoldUserBundle:User:index" }

admin_show:
    path:     /{id}/show
    defaults: { _controller: "InfogoldUserBundle:User:show" }

admin_new:
    path:     /new
    defaults: { _controller: "InfogoldUserBundle:User:new" }

admin_create:
    path:     /create
    defaults: { _controller: "InfogoldUserBundle:User:create" }
    requirements: { _method: post }

admin_edit:
    path:     /{id}/edit
    defaults: { _controller: "InfogoldUserBundle:User:edit" }

admin_update:
    path:     /{id}/update
    defaults: { _controller: "InfogoldUserBundle:User:update" }
    requirements: { _method: post|put }

admin_delete:
    path:     /{id}/delete
    defaults: { _controller: "InfogoldUserBundle:User:delete" }
    requirements: { _method: post|delete }
