## YAML Template.
---
    # category
    
category_index:
   path:     /
   defaults: { _controller: "InfogoldAccountBundle:Category:index" }
   methods:  GET

category_show:
   path:     /{id}/show
   defaults: { _controller: "InfogoldAccountBundle:Category:show" }
   methods:  GET

category_new:
   path:     /new
   defaults: { _controller: "InfogoldAccountBundle:Category:new" }
   methods:  [GET, POST]

category_edit:
   path:     /{id}/edit
   defaults: { _controller: "InfogoldAccountBundle:Category:edit" }
   methods:  [GET, POST]

category_delete:
   path:     /{id}/delete
   defaults: { _controller: "InfogoldAccountBundle:Category:delete" }
   methods:  DELETE